# Generated by Django 3.0.6 on 2022-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20220207_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='method_of_preparing',
            field=models.TextField(null=True),
        ),
    ]
